services:
  weaviate:
    container_name: weaviate
    image: semitechnologies/weaviate:stable-v1.31-21d208c
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      DEFAULT_VECTORIZER_MODULE: "none"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DISABLE_TELEMETRY: "true"
      CLUSTER_HOSTNAME: "node1"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: unless-stopped

  app:
    container_name: rag-weather-assistant
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      AZURE_OPENAI_EMBEDDING_ENDPOINT: ${AZURE_OPENAI_EMBEDDING_ENDPOINT}
    ports:
      - "5000:5000"
    depends_on:
      - weaviate
    restart: unless-stopped

volumes:
  weaviate-data:
